### ISSUE TITLE
Please use GNU/Linux instead of Linux

### ISSUE THREAD

**Issue by bekatoros** [lmanul/whylinuxisbetter#10]
Hi, I want to make a request of changing the titles of Linux that is the operating system's kernel to GNU/Linux that is the name of the Operating System.
You can read more about this in http://www.gnu.org/gnu/why-gnu-linux.en.html

**Comment by lmanul** [comment]
Hi there,

Thanks for the comment! I've considered this before and this page covers it:

    http://whylinuxisbetter.net/faq.php#gnu

Let me know what you think. :)
