### ISSUE TITLE
Missing image extensin in source link.

### ISSUE THREAD

**Issue by Labonte-LucPaul** [lmanul/whylinuxisbetter#12]
https://github.com/lmanul/whylinuxisbetter/blob/master/items/gaim_im_services/index.php#L18

Missing ``.png`` extension: ```<img src="Images/gaim_im_services" />```

This issue is present in all of the indexes pages in the ``/Items/gaim_im_services`` page.

**Comment by lmanul** [comment]
Should be fixed now. thanks for the report!!
