### ISSUE TITLE
Features are not specific to Linux.

### ISSUE THREAD

**Issue by mzs114** [lmanul/whylinuxisbetter#15]
Hi,
Many things on the site are applicable to BSDs or they are not Linux specific. 
Please mention this.
Perhaps we can make the content distribution or flavor neutral.

**Comment by lmanul** [comment]
Thanks for the report! Pull requests welcome :-)

**Comment by mzs114** [comment]
Closing the ticket goes to show how reasoning was put aside.

**Comment by lmanul** [comment]
The website is clearly about Linux (as mentioned in its name). The proposed changes were about pointing out that BSD had some of the same features. That's obviously true, but probably not relevant to this particular website. Many other OSes and code bases also share some similar characteristics, I don't see it necessary to list them all. Reasoning isn't being put aside.
