### ISSUE TITLE
Clunky Language

### ISSUE THREAD

**Issue by boojiboy** [lmanul/whylinuxisbetter#20]
You should consider adding each language as a GET variable to a single file, and then mask it in .htaccess instead of having an individual file for _every_ language. 
e.g. index.php?lang=ru --> home/ru/
       faq.php?lang=ar --> faq/ar/

It looks cleaner, and is easier to manage styling within a page (changing it once, instead of changing in 20+ times)

**Comment by lmanul** [comment]
Very much agreed! Pull requests welcome ;-)

**Comment by apfeltee** [comment]
Speaking of which, maybe even do it using a static site generator, so that each page can be written in a markup language (such as markdown)?
That'd eliminate the need for PHP altogether, and makes building/publishing quite a bit easier, at least in my experience.

**Comment by lmanul** [comment]
No more PHP now. If you'd like to fix my shaky English, pull requests are very welcome!
