### ISSUE TITLE
Issue with "no big mess in your start menu"

### ISSUE THREAD

**Issue by jcjordyn130** [lmanul/whylinuxisbetter#22]
The desktop environment displayed is gnome 2. Ubuntu now uses unity. Wouldn’t this argument be invalid?

**Comment by lmanul** [comment]
That's a fair point indeed! Would you be ready to send a patch to either fix or remove this part? :-)

**Comment by jcjordyn130** [comment]
Yes

**Comment by jcjordyn130** [comment]
Hey I am making a patch for it. I found a image of the unity dash, but it can't upload it.

**Comment by iamunknown2** [comment]
But then, there's MATE, which is a fork of GNOME 2.'

You should include GNOME 3 (for people who may want something a bit different) and Cinnamon.

**Comment by jcjordyn130** [comment]
Yes, but how am I going to put a picture up?

**Comment by jcjordyn130** [comment]
Okay the pull request it up.
