### ISSUE TITLE
Someone was GAUGHT SLANDERING on Linux ON PURPOSE

### ISSUE THREAD

**Issue by gencube** [lmanul/whylinuxisbetter#25]
Its ALSO targeting THIS Website.
Should we make these Channels INFAMOUS???
https://www.facebook.com/photo.php?fbid=10153732459353403&set=a.10150773013033403.401482.661063402&type=3&theater

**Comment by lmanul** [comment]
Is this an issue specifically with the code for this website? I fail to see how this could be "fixed" within the realm of this project.
