### ISSUE TITLE
suggestion concerning the page about games

### ISSUE THREAD

**Issue by gilbertohasnofb** [lmanul/whylinuxisbetter#6]
A suggestion concerning the page about games (http://www.whylinuxisbetter.net/stick_to_windows/hardcore_gamer/): I would certainly rewrite some information in that page since as of now Linux games are becoming more and more common. Steam currently has 1572 Linux titles (December 2014), including several major releases, and several other major gaming websites sell Linux games (humblebundle, gog.com, etc.). Surely Linux has not catch up with Windows in the gaming sector yet, but that page in your website sounds as if the situation is the same as 10 years ago. Out of all the games I am interested, there is only a single one which is Windows only. So I wouldn't recommend a gamer to stay on Windows, I would simply recommend him or her to check if their favourite games are available on Linux or not.

**Comment by P1raten** [comment]
Currently there are 2175 titles who support Linux on Steam.

That's in increase of 603, which is roughly 120 new linux games each month.

**Comment by lmanul** [comment]
Hi guys,

Thanks a lot for your comments! This is covered here:

    http://whylinuxisbetter.net/faq.php#gaming

Let me know what you think. :-)

**Comment by P1raten** [comment]
Good that you clarified what you ment by "hardcore gamer". In my eyes a hardcore gamer could be someone who is dedicated to one specific title, which shouldn't be seen as a setback when using Linux.
