### ISSUE TITLE
Be a bit more precise on some arguments

### ISSUE THREAD

**Issue by MightyCreak** [lmanul/whylinuxisbetter#9]
Some guy says that some of the arguments on whylinuxisbetter.net are not entirely true and that most of the newcomers will be disappointed by some false-promises that Linux users often say to people interested in testing Linux.

Here is the video: https://www.youtube.com/watch?v=y_lhqg_p21k

I think the guy didn't really understand why defragmentation isn't a problem in Linux, but to be fair, NTFS doesn't need defragmentation either... Also, you might think he is wrong about the viruses because the viruses that are detected are in .exe and .dll files, but when you think of it, the application didn't work before and did work after a virus scan. To a newcomer, this means that virus _can_ affect Linux systems.

Well, this is not about trolling, but more about having some productive discussion about that.

Thanks!

**Comment by aaronfranke** [comment]
NTFS doesn't need defragmentation? It very much DOES, actually. Newer versions of Windows will do this automatically and defragmentation isn't necessary to speed up performance on an SSD, however fragmentation still isn't a healthy thing for the filesystem. In all drive types, it's beneficial to not have the filesystem fragment in the first place.

I don't really get the argument for the .dll/exe's presence meaning that Linux has viruses. That program tries to load things in there by its own design. You could replace any config file with gibberish and it'll stop that program from loading, but you wouldn't call that malware would you?

**Comment by MightyCreak** [comment]
OK for me to have a nice discussion ;)

The time, back on Windows XP, where we needed to defrag our hard drives every 3 months is quite over. I admit NTFS isn't as smart as ext4 for it, but I honestly don't see any interest in defragging a hard drive that isn't almost full, and for what it takes, when a disk is almost full it'd be better to change the disk altogether (no matter the file system).

> File systems such as NTFS are designed to decrease the likelihood of fragmentation.[3][4] 

-- https://en.wikipedia.org/wiki/Defragmentation#User_and_performance_issues

As for the viruses argument I think that, from a user stand point, an application that prevents from using another application looks like a virus. But whether you're convinced or not by the video, I just won't say that there aren't any viruses on Linux. The design is better under Linux, but one small security breach in an application running as root and you're entire machine is vulnerable. And Xorg is known to have had security issues. They've been fixed, of course, but I'm fairly sure there are others lying in this huge, monolithic source code.

My idea is not to invalid any argument on whylinuxisbetter, but simply to put some subtlety in them. Newcomers won't like it when they'll understand the truth they've read is not exactly the real truth but just a beautified one.

**Comment by MathManiac0** [comment]
@MightyCreak I created Pull Request #19 inspired by the video... Do leave suggestions!
